# Generated by Django 4.2.25 on 2025-10-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_remove_song_categories_remove_song_tags_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='song',
            name='script',
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(choices=[('tamil', 'Tamil'), ('telugu', 'Telugu'), ('english', 'English')], default='tamil', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='script_tamil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
