# Generated by Django 4.2.25 on 2025-10-24 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0006_userprofile_songaccess_accessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='category',
            field=models.CharField(choices=[('ayyappa', 'Ayyappa'), ('siva', 'Siva'), ('amman', 'Amman'), ('murugan', 'Murugan'), ('venkateswara', 'Venkateswara'), ('others', 'Others')], default='others', help_text='Deity/Theme category', max_length=20),
        ),
        migrations.CreateModel(
            name='Saranaghosha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ta', models.CharField(blank=True, max_length=255, verbose_name='Tamil Title')),
                ('title_te', models.CharField(blank=True, max_length=255, verbose_name='Telugu Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English Title')),
                ('content_ta', models.TextField(blank=True, verbose_name='Tamil Content')),
                ('content_te', models.TextField(blank=True, verbose_name='Telugu Content')),
                ('content_en', models.TextField(blank=True, verbose_name='English Content')),
                ('language', models.CharField(choices=[('tamil', 'Tamil'), ('telugu', 'Telugu'), ('english', 'English')], default='tamil', max_length=20)),
                ('category', models.CharField(choices=[('ayyappa', 'Ayyappa'), ('siva', 'Siva'), ('amman', 'Amman'), ('murugan', 'Murugan'), ('venkateswara', 'Venkateswara'), ('others', 'Others')], default='others', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saranagoshas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saranaghosha',
                'verbose_name_plural': 'Saranagoshas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Astotharam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ta', models.CharField(blank=True, max_length=255, verbose_name='Tamil Title')),
                ('title_te', models.CharField(blank=True, max_length=255, verbose_name='Telugu Title')),
                ('title_en', models.CharField(blank=True, max_length=255, verbose_name='English Title')),
                ('content_ta', models.TextField(blank=True, verbose_name='Tamil Content')),
                ('content_te', models.TextField(blank=True, verbose_name='Telugu Content')),
                ('content_en', models.TextField(blank=True, verbose_name='English Content')),
                ('language', models.CharField(choices=[('tamil', 'Tamil'), ('telugu', 'Telugu'), ('english', 'English')], default='tamil', max_length=20)),
                ('category', models.CharField(choices=[('ayyappa', 'Ayyappa'), ('siva', 'Siva'), ('amman', 'Amman'), ('murugan', 'Murugan'), ('venkateswara', 'Venkateswara'), ('others', 'Others')], default='others', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astotharams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Astotharam',
                'verbose_name_plural': 'Astotharams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_categories', models.JSONField(blank=True, default=list, help_text='Custom deity categories')),
                ('primary_color', models.CharField(default='#d97706', help_text='Primary theme color (hex)', max_length=7)),
                ('secondary_color', models.CharField(default='#f59e0b', help_text='Secondary theme color (hex)', max_length=7)),
                ('site_title', models.CharField(default='Swamiye Saranam Ayyappa', max_length=100)),
                ('site_subtitle', models.CharField(blank=True, default='Devotional Songs Collection', max_length=200)),
                ('enable_categories', models.BooleanField(default=True)),
                ('enable_astotharam', models.BooleanField(default=True)),
                ('enable_saranaghosha', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'App Settings',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
