# Generated by Django 4.2.25 on 2025-10-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact',
            field=models.CharField(blank=True, help_text='Mobile number', max_length=20, unique=True),
        ),
    ]
