# Generated by Django 4.2.25 on 2025-10-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_userprofile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
