# Generated by Django 4.2.25 on 2025-10-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_delete_category_delete_tag_remove_song_script_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('file', 'Uploaded File'), ('youtube', 'YouTube URL'), ('url', 'External URL')], default='file', max_length=20)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True, unique=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_count', models.IntegerField(default=0, help_text='Number of songs using this audio')),
            ],
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='song',
            name='script_english',
        ),
        migrations.RemoveField(
            model_name='song',
            name='script_tamil',
        ),
        migrations.RemoveField(
            model_name='song',
            name='script_telugu',
        ),
        migrations.RemoveField(
            model_name='song',
            name='title',
        ),
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Mark as favorite for quick access'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_en',
            field=models.TextField(blank=True, verbose_name='English Lyrics'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_ta',
            field=models.TextField(blank=True, verbose_name='Tamil Lyrics'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_te',
            field=models.TextField(blank=True, verbose_name='Telugu Lyrics'),
        ),
        migrations.AddField(
            model_name='song',
            name='play_count',
            field=models.IntegerField(default=0, help_text='Number of times played'),
        ),
        migrations.AddField(
            model_name='song',
            name='title_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='English Title'),
        ),
        migrations.AddField(
            model_name='song',
            name='title_ta',
            field=models.CharField(blank=True, max_length=255, verbose_name='Tamil Title'),
        ),
        migrations.AddField(
            model_name='song',
            name='title_te',
            field=models.CharField(blank=True, max_length=255, verbose_name='Telugu Title'),
        ),
        migrations.AddField(
            model_name='song',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['language'], name='songs_song_languag_1e13b6_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_favorite'], name='songs_song_is_favo_da0bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['-uploaded_at'], name='songs_song_uploade_733da5_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['youtube_url'], name='songs_audio_youtube_3cb4e1_idx'),
        ),
        migrations.AddIndex(
            model_name='audiofile',
            index=models.Index(fields=['source_type'], name='songs_audio_source__863b64_idx'),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='songs.audiofile'),
        ),
    ]
